export const browserCoreExamples = [
  "soulclaw browser status",
  "soulclaw browser start",
  "soulclaw browser stop",
  "soulclaw browser tabs",
  "soulclaw browser open https://example.com",
  "soulclaw browser focus abcd1234",
  "soulclaw browser close abcd1234",
  "soulclaw browser screenshot",
  "soulclaw browser screenshot --full-page",
  "soulclaw browser screenshot --ref 12",
  "soulclaw browser snapshot",
  "soulclaw browser snapshot --format aria --limit 200",
  "soulclaw browser snapshot --efficient",
  "soulclaw browser snapshot --labels",
];

export const browserActionExamples = [
  "soulclaw browser navigate https://example.com",
  "soulclaw browser resize 1280 720",
  "soulclaw browser click 12 --double",
  'soulclaw browser type 23 "hello" --submit',
  "soulclaw browser press Enter",
  "soulclaw browser hover 44",
  "soulclaw browser drag 10 11",
  "soulclaw browser select 9 OptionA OptionB",
  "soulclaw browser upload /tmp/openclaw/uploads/file.pdf",
  'soulclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "soulclaw browser dialog --accept",
  'soulclaw browser wait --text "Done"',
  "soulclaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "soulclaw browser console --level error",
  "soulclaw browser pdf",
];
