export const browserCoreExamples = [
  "lumaclaw browser status",
  "lumaclaw browser start",
  "lumaclaw browser stop",
  "lumaclaw browser tabs",
  "lumaclaw browser open https://example.com",
  "lumaclaw browser focus abcd1234",
  "lumaclaw browser close abcd1234",
  "lumaclaw browser screenshot",
  "lumaclaw browser screenshot --full-page",
  "lumaclaw browser screenshot --ref 12",
  "lumaclaw browser snapshot",
  "lumaclaw browser snapshot --format aria --limit 200",
  "lumaclaw browser snapshot --efficient",
  "lumaclaw browser snapshot --labels",
];

export const browserActionExamples = [
  "lumaclaw browser navigate https://example.com",
  "lumaclaw browser resize 1280 720",
  "lumaclaw browser click 12 --double",
  'lumaclaw browser type 23 "hello" --submit',
  "lumaclaw browser press Enter",
  "lumaclaw browser hover 44",
  "lumaclaw browser drag 10 11",
  "lumaclaw browser select 9 OptionA OptionB",
  "lumaclaw browser upload /tmp/openclaw/uploads/file.pdf",
  'lumaclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "lumaclaw browser dialog --accept",
  'lumaclaw browser wait --text "Done"',
  "lumaclaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "lumaclaw browser console --level error",
  "lumaclaw browser pdf",
];
